### ISSUE TITLE
Publish on Google Play or F-Droid so I can try? Is the app ready?

### ISSUE THREAD

**Issue by w-jablonski** [sndnv/eventually#14]
Thanks!

**Comment by sndnv** [comment]
Hi,

Thanks for opening this issue and it is a fair point, but I have no immediate plans to publish the app on any app store.

As for the app being ready or not, I have been using it for a couple of years on my own devices and it's been fine so far (it has also been tested on API levels 26, 28, 29 and 30).

You can give it a try by installing the apk published with each [release](https://github.com/sndnv/eventually/releases) but keep in mind it is signed by myself so not exactly a "trusted" source =] Alternatively, you can clone the repo and build/sign an apk yourself via Android Studio.

**Comment by w-jablonski** [comment]
I will try to install it from source when time allows me to dig into it. Thanks! 

EDIT: Oh I see the releases actually contain an .apk file!
